'use client';

import type { StoryBeat } from '../lib/story-generator';
import type { Panel } from '../lib/types';

const toneColor: Record<StoryBeat['tone'], string> = {
  calm: 'bg-sky-500/10 text-sky-200 border border-sky-500/30',
  tense: 'bg-orange-500/10 text-orange-200 border border-orange-500/30',
  triumphant: 'bg-emerald-500/10 text-emerald-200 border border-emerald-500/30',
};

export type StoryboardProps = {
  beats: StoryBeat[];
  panels: Panel[];
};

export function Storyboard({ beats, panels }: StoryboardProps) {
  if (!beats.length) return null;
  const panelLookup = new Map(panels.map((panel) => [panel.id, panel] as const));

  return (
    <section className="space-y-2">
      <header className="flex items-baseline justify-between">
        <h3 className="text-sm font-semibold uppercase tracking-wide text-ink-400">Narrative Beats</h3>
        <span className="text-xs text-ink-500">Autogenerated mood arc</span>
      </header>
      <ol className="grid gap-3 md:grid-cols-2">
        {beats.map((beat, index) => (
          <li key={beat.id} className={`rounded-2xl p-4 backdrop-blur ${toneColor[beat.tone]}`}>
            <p className="text-xs font-semibold uppercase tracking-wide text-ink-400">Beat {index + 1}</p>
            <p className="mt-2 text-sm leading-relaxed text-ink-100">{beat.narration}</p>
            {panelLookup.has(beat.panelId) ? (
              <p className="mt-3 text-xs text-ink-500">
                Panel focus: {(panelLookup.get(beat.panelId)?.emphasis ?? 0).toFixed(2)}
              </p>
            ) : null}
          </li>
        ))}
      </ol>
    </section>
  );
}
